{...}: {
  # Force the symlink so Zed cannot leave behind the autogenerated file it writes
  # on first launch.
  xdg.configFile."zed/settings.json" = {
    source = ./zed/settings.json;
    force = true;
  };
}
